@startuml
!theme mars
class GameCharacter
    
note "Oberklasse" as N1 

class NonPlayerCharacter



class PlayerCharacter


GameCharacter <-- NonPlayerCharacter
GameCharacter <-- PlayerCharacter
note " " as N2

hide GameCharacter circle
hide GameCharacter fields
hide GameCharacter methods
hide NonPlayerCharacter circle
hide NonPlayerCharacter fields
hide NonPlayerCharacter methods
hide PlayerCharacter circle
hide PlayerCharacter fields
hide PlayerCharacter methods
hide N2
note "Unterklassen" as N3
@enduml
